var = input("Insira algo: ")
print("")
print("Condições")
print(type(var))
print("Número:", var.isnumeric())
print("Alfabético:", var.isalpha())
print("Alfanúmerico:", var.isalnum())
print("Espaço:", var.isspace())
print("Maiúscula:", var.isupper())
print("Minúscula:", var.islower())
print("Capitalizada:", var.istitle())